"""Generate a figure config for every MALIBU3D ROI in a drop.

The ROIs differ in extent (25 to 150 subtiles) and in point density (0.12 to
0.26 m spacing), so a camera and sphere radius copied from one tile do not
transfer. Both are derived here from each cloud's own geometry, anchored on the
hand-tuned reference tile:

  * camera   — the reference pose, with its distance scaled by the ROI's XY
               extent, so every tile is framed the same way
  * voxel    — the reference radius-to-spacing ratio, times this ROI's spacing,
               times sqrt(n_full / n_kept) when subsampling

    python scripts/prepare_rois.py --drop data/malibu3d/send_29_07_v2/blender_export
"""
import argparse
import glob
import json
import math
import os
import os.path as osp
import sys

import numpy as np

sys.path.insert(0, osp.dirname(osp.dirname(osp.abspath(__file__))))
from figlib import load_config, load_point_cloud     # noqa: E402

# The hand-tuned reference: pose, and the ROI extent it was framed for
REFERENCE = "malibu3d_D075_UU-S1-3"
REFERENCE_EXTENT = 512.0

# One hue per network type, so the three read apart when several are shown
GRAPH_COLORS = {
    "roads": [0.30, 0.55, 1.00],
    "railroads": [1.00, 0.45, 0.25],
    "transmission": [1.00, 0.85, 0.25],
}


def main(args):
    reference = load_config(f"configs/figures/{REFERENCE}.yaml")
    ref_camera = reference["camera"]
    ref_translation = np.asarray(ref_camera["translation"], dtype=float)
    ref_voxel = float(reference["data"]["voxel"])

    rois = sorted(glob.glob(osp.join(args.drop, "*", "*_meta.json")))
    print(f"Found {len(rois)} ROI sidecars in {args.drop}\n")

    written, skipped = [], []
    for meta_path in rois:
        directory = osp.dirname(meta_path)
        roi = osp.basename(meta_path).replace("_meta.json", "")
        ply = osp.join(directory, f"{roi}.ply.gz")
        if not osp.exists(ply):
            print(f"  {roi}: SKIP — no point cloud ({osp.basename(ply)} missing)")
            skipped.append(roi)
            continue

        name = f"malibu3d_{roi}"
        path = osp.join("configs", "figures", f"{name}.yaml")
        # Never clobber a config whose camera has been tuned by hand. Checked
        # before loading, so re-running over a processed drop is instant.
        if name == REFERENCE or (osp.exists(path) and not args.overwrite):
            print(f"  {roi}: keeping existing {osp.basename(path)}")
            written.append(name)
            continue

        cloud = load_point_cloud(
            ply,
            palettes=osp.join(args.drop, "palettes.json"),
            cache_dir=args.cache_dir,
            log=lambda m: None)
        cloud.drop_void(["elevation"], log=lambda m: None)

        extent = cloud.pos.max(0) - cloud.pos.min(0)
        extent_xy = float(max(extent[0], extent[1]))
        n_points = len(cloud)
        spacing = math.sqrt((extent[0] * extent[1]) / n_points)

        keep = min(n_points, args.max_points)
        thinning = math.sqrt(n_points / keep)
        voxel = ref_voxel * (spacing / (REFERENCE_EXTENT / math.sqrt(3972917))) * thinning
        # the reference ratio expressed directly, to avoid drift if it changes
        voxel = round(spacing * (ref_voxel / 0.2570) * thinning, 3)

        scale = extent_xy / REFERENCE_EXTENT
        translation = (ref_translation * scale).round(4).tolist()

        graphs = [osp.relpath(p) for p in sorted(
            glob.glob(osp.join(directory, f"{roi}_*_graph.gpkg")))]

        with open(path, "w") as f:
            f.write(f"""# MALIBU3D ROI {roi} — auto-generated by scripts/prepare_rois.py
# {extent_xy:.0f} x {float(extent[1]):.0f} m, {n_points} points, {spacing:.3f} m spacing.
# Camera is the {REFERENCE} pose scaled x{scale:.2f} for this ROI's extent —
# a starting point, not a tuned view. Refine it in the GUI and pull it back with
# scripts/scene_to_config.py.
extends: ../malibu3d.yaml

data:
  path: {osp.relpath(ply)}
  voxel: {voxel}
""")
            if keep < n_points:
                f.write(f"  subsample: {keep}   "
                        f"# of {n_points}; voxel already scaled by sqrt(n_full/n_kept)\n")
            f.write(f"""
camera:
  translation: {translation}
  quaternion: {[round(v, 7) for v in ref_camera['quaternion']]}
  fov_x_deg: {ref_camera['fov_x_deg']}
  near: {ref_camera['near']}
  far: {max(1000, int(extent_xy * 4))}
""")
            # Networks actually get drawn, not just listed. A ROI with no
            # graph file simply gets no `graphs:` block, and the figure script
            # skips the whole stage — no crash.
            if graphs:
                f.write("\ngraphs:\n  items:\n")
                for path_g in graphs:
                    kind = "roads"
                    upper = osp.basename(path_g).upper()
                    if "RAILROAD" in upper:
                        kind = "railroads"
                    elif "TRANSMISSION" in upper:
                        kind = "transmission"
                    colour = GRAPH_COLORS.get(kind, GRAPH_COLORS["roads"])
                    f.write(f"    - path: {path_g}\n")
                    f.write(f"      name: {kind}_gt\n")
                    f.write(f"      color: {colour}\n")
            else:
                f.write("\n# No network graph delivered for this ROI.\n")

        print(f"  {roi}: {n_points:>9} pts, {extent_xy:6.0f} m, spacing {spacing:.3f} m "
              f"-> voxel {voxel}, keep {keep}, camera x{scale:.2f}")
        written.append(name)
        del cloud

    print(f"\nWrote {len(written)} configs; skipped {len(skipped)}: {skipped}")
    return written


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--drop", required=True, help="blender_export directory")
    parser.add_argument("--max-points", type=int, default=8_000_000,
                        help="Cap for preview renders (default 8M)")
    parser.add_argument("--cache-dir", default="data/.figcache")
    parser.add_argument("--overwrite", action="store_true",
                        help="Replace configs that already exist (never the reference)")
    main(parser.parse_args())
