"""Verify the figure pipeline's invariants. Run after touching render or export.

Every check here exists because the corresponding bug was actually shipped:

  configs        every figure config loads and resolves
  identity       an ungraded layer renders EXACTLY as a bare Attribute->BSDF
                 material would  (caught: contrast 1.0 vs 0.0 semantics)
  not-black      every layer renders with real colour, not just lighting
                 (caught: shader reading a colour attribute that only exists
                  in exports, which rendered near-black)
  material       the grading chain survives a colour reassignment
                 (caught: blender_plots builds a new material every time)
  export         the .blend carries every layer, the grading table, the active
                 layer, and the grading nodes
  graphs         graphs declared in the config are actually drawn
                 (caught: paths written as YAML comments, never as items)
  parenting      graph node spheres are parented to their edges, so height
                 moves the whole graph  (caught: nodes left behind)
  roundtrip      export -> read back gives the same numbers
  degenerate     a ROI with no graph, and a config restricting data.colors,
                 both work rather than crashing

    python scripts/selfcheck.py                    # quick, one representative tile
    python scripts/selfcheck.py --all-configs      # also load every figure config
"""
import argparse
import glob
import json
import os
import os.path as osp
import subprocess
import sys
import tempfile

import numpy as np

sys.path.insert(0, osp.dirname(osp.dirname(osp.abspath(__file__))))
from figlib import load_config                                    # noqa: E402

PY = osp.expanduser("~/miniconda3/envs/blendify/bin/python")
SCRIPT = "examples/00_custom.py"

# A small tile that has graphs, so graph checks are meaningful
TILE = "configs/figures/malibu3d_D075_FU-S1-10.yaml"
TILE_NO_GRAPH = "configs/figures/malibu3d_D073_NN-S1-5.yaml"

PASS, FAIL = "PASS", "FAIL"
results = []

# Outputs are named after the config, so the checks run against throwaway
# configs that extend the real ones. Without this the self-check EXPORTS OVER
# the real .blend and PNGs with tiny test-sized versions — it did, and silently
# replaced a 5.5 M-point export with a 120 k one.
TEMP_PREFIX = "_selfcheck_"
_temp_configs = []


def temp_config(base_config, tag, overrides=None):
    """A disposable config extending `base_config`, so outputs land elsewhere."""
    path = osp.join("configs", "figures", f"{TEMP_PREFIX}{tag}.yaml")
    lines = [f"# Generated by scripts/selfcheck.py — safe to delete.",
             f"extends: {osp.basename(base_config)}", ""]
    for section, values in (overrides or {}).items():
        lines.append(f"{section}:")
        for key, value in values.items():
            lines.append(f"  {key}: {value!r}")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    _temp_configs.append(path)
    return path


def cleanup_temp(*cfgs_for_paths):
    """Remove the throwaway configs and everything they wrote.

    Every config the checks touch has its own data directory, so all of them
    must be swept — cleaning only the first left files behind.
    """
    import glob as _glob
    removed = 0
    for cfg in cfgs_for_paths:
        try:
            data_dir = osp.dirname(load_config(cfg)["data"]["path"])
            for path in _glob.glob(osp.join(data_dir, f"{TEMP_PREFIX}*")):
                os.remove(path)
                removed += 1
        except Exception:                                         # noqa: BLE001
            continue
    for path in _temp_configs:
        if osp.exists(path):
            os.remove(path)
            removed += 1
    return removed


def record(name, ok, detail=""):
    results.append((PASS if ok else FAIL, name, detail))
    print(f"  [{PASS if ok else FAIL}] {name}" + (f"  — {detail}" if detail else ""))
    return ok


def run(args, timeout=1800):
    return subprocess.run(args, capture_output=True, text=True, timeout=timeout)


def render(config, out_dir, extra=(), samples=8, resolution=(300, 200),
           subsample=120000):
    """Render layers of `config` into `out_dir`; returns {layer: path}."""
    overrides = [
        f"data.subsample={subsample}",
        f"render.n_samples={samples}",
        f"render.resolution=[{resolution[0]},{resolution[1]}]",
        *extra,
    ]
    result = run([PY, SCRIPT, "--config", config, "--image",
                  "--set", *overrides,
                  "--path-out", out_dir] if False else
                 [PY, SCRIPT, "--config", config, "--image", "--set", *overrides])
    if result.returncode != 0:
        return None, result.stderr[-1500:]
    # Outputs are named after the CONFIG (see 00_custom.py), not the data file.
    # Layer names contain underscores (natural_habitat, rgb_muted), so strip the
    # known stem rather than splitting on the last underscore.
    stem = osp.basename(config).rsplit(".", 1)[0]
    if stem.startswith("malibu3d_"):
        stem = stem[len("malibu3d_"):]
    produced = {}
    for line in result.stdout.splitlines():
        if line.startswith("Saved: '"):
            path = line.split("Saved: '", 1)[1].rstrip("'")
            name = osp.basename(path)[:-len(".png")]
            layer = name[len(stem) + 1:] if name.startswith(stem + "_") else name
            produced[layer] = path
    return produced, result.stdout


def mean_colour(path):
    import matplotlib.image as mpimg
    img = mpimg.imread(path)
    mask = img[..., 3] > 0.5
    if mask.sum() == 0:
        return None
    return img[..., :3][mask].mean()


def check_configs(all_configs):
    print("\nconfigs")
    configs = sorted(glob.glob("configs/figures/*.yaml"))
    if not all_configs:
        configs = configs[:3] + [TILE, TILE_NO_GRAPH]
    bad = []
    for path in set(configs):
        try:
            cfg = load_config(path)
            for section in ("data", "render", "camera", "sun", "world",
                            "point_cloud", "color", "void", "graphs", "export"):
                if section not in cfg:
                    bad.append(f"{osp.basename(path)}: missing {section}")
        except Exception as exc:                                  # noqa: BLE001
            bad.append(f"{osp.basename(path)}: {exc}")
    record(f"{len(set(configs))} configs load and resolve", not bad,
           "; ".join(bad[:3]))


def check_render_and_identity(tmp):
    print("\nrender")
    cfg = load_config(SAFE_TILE)
    graded = set(cfg["color"]["apply_to"] or [])

    produced, log = render(SAFE_TILE, tmp, extra=["graphs.items=[]"])
    if produced is None:
        record("all layers render", False, log)
        return
    expected = {"rgb", "elevation", "forest", "natural_habitat", "semantic",
                "xyz", "grayscale", "rgb_muted"}
    missing = expected - set(produced)
    record(f"all {len(expected)} layers render", not missing,
           f"missing {sorted(missing)}" if missing else "")

    # not-black: a layer showing only lighting has almost no colour
    # A near-transparent layer (rgb_muted at alpha 0.05) has no opaque pixels to
    # measure, so mean_colour returns None there — not a failure.
    dark = {}
    for name, path in produced.items():
        if name == "rgb_muted":
            continue
        value = mean_colour(path)
        if value is not None and value < 0.05:
            dark[name] = round(value, 4)
    record("no layer renders black", not dark, f"suspicious: {dark}" if dark else "")

    # identity: an ungraded layer must match a bare material exactly
    baseline = osp.join(tmp, "elevation_baseline.png")
    ungraded = [k for k in produced if k not in graded and k != "rgb_muted"]
    if "elevation" in ungraded:
        import shutil
        shutil.copy(produced["elevation"], baseline)
        again, _ = render(SAFE_TILE, tmp, extra=["graphs.items=[]",
                                            "data.colors=['elevation']",
                                            "data.default_color=elevation",
                                            "data.add_xyz=False"])
        if again and "elevation" in again:
            import matplotlib.image as mpimg
            a, b = mpimg.imread(baseline), mpimg.imread(again["elevation"])
            mask = (a[..., 3] > 0.5) & (b[..., 3] > 0.5)
            delta = float(np.abs(a[..., :3][mask] - b[..., :3][mask]).max())
            record("ungraded layer is reproducible", delta < 0.02,
                   f"max |diff| {delta:.4f}")
        else:
            record("ungraded layer is reproducible", False, "second render failed")

    # Saturation must actually desaturate. Measured on a highly chromatic layer
    # under neutral light: a photo layer of dark forest is already near-grey, so
    # testing there cannot distinguish "working" from "no-op" (it did not, and
    # produced a false alarm).
    chroma = {}
    for value in (1.0, 0.0):
        got, _ = render(SAFE_TILE, tmp, extra=[
            "graphs.items=[]", "data.colors=['semantic']",
            "data.default_color=semantic", "data.add_xyz=False",
            "color.variants=[]", "color.apply_to=['semantic']",
            f"color.saturation={value}",
            "sun.color=[1.0,1.0,1.0]", "world.color=[1.0,1.0,1.0]"])
        if not got or "semantic" not in got:
            record("saturation node desaturates", False, "render failed")
            return
        import matplotlib.image as mpimg
        img = mpimg.imread(got["semantic"])
        mask = img[..., 3] > 0.5
        px = img[..., :3][mask]
        chroma[value] = float(np.abs(px - px.mean(1, keepdims=True)).mean())
    ratio = chroma[0.0] / max(chroma[1.0], 1e-9)
    record("saturation node desaturates", ratio < 0.2,
           f"chromaticity {chroma[1.0]:.4f} -> {chroma[0.0]:.4f} (ratio {ratio:.3f})")


def check_export_and_roundtrip(tmp):
    print("\nexport + round-trip")
    result = run([PY, SCRIPT, "--config", SAFE_TILE, "--export"])
    if result.returncode != 0:
        record("export succeeds", False, result.stderr[-800:])
        return
    record("export succeeds", True)

    cfg = load_config(SAFE_TILE)
    stem = osp.basename(SAFE_TILE).rsplit(".", 1)[0]
    blend = osp.join(osp.dirname(cfg["data"]["path"]), stem + ".blend")

    probe = osp.join(tmp, "probe.py")
    out_json = osp.join(tmp, "probe.json")
    with open(probe, "w") as f:
        f.write(f'''
import bpy, json
scene = bpy.context.scene
cloud = [o for o in scene.objects if o.type=="MESH" and o.name.startswith("point_cloud")][0]
mat = bpy.data.materials["color"]
nodes = [n.name for n in mat.node_tree.nodes]
graphs = {{}}
for o in scene.objects:
    if o.type == "CURVE" and o.name.endswith("_edges"):
        graphs.setdefault(o.name[:-6], {{}})["height"] = round(o.location.z, 4)
    if o.type == "MESH" and o.name.endswith("_nodes"):
        graphs.setdefault(o.name[:-6], {{}})["parent"] = o.parent.name if o.parent else None
# palette editing: identity recolour must be a no-op, an edit must move exactly
# the edited class, and alpha (the void fading) must survive
palette_ok, palette_detail = None, ""
try:
    import numpy as np
    tables = json.loads(cloud.get("figure_palettes") or "{{}}")
    layer = next(iter(tables))
    entry = tables[layer]
    me = cloud.data; n = len(me.vertices)
    attr = me.color_attributes[f"color_{{layer}}"]
    idx_attr = me.attributes[f"class_{{layer}}"]
    labels = np.empty(n, np.int32); idx_attr.data.foreach_get("value", labels)
    base = np.empty(n*4, np.float32); attr.data.foreach_get("color", base)

    def apply(lut):
        arr = np.asarray(lut, np.float32)
        cur = np.empty(n*4, np.float32); attr.data.foreach_get("color", cur)
        out = np.empty((n,4), np.float32)
        out[:, :3] = arr[np.clip(labels,0,len(arr)-1)]
        out[:, 3] = cur.reshape(n,4)[:,3]
        attr.data.foreach_set("color", out.ravel())

    apply(entry["colors"])
    same = np.empty(n*4, np.float32); attr.data.foreach_get("color", same)
    d_identity = float(np.abs(base-same).max())

    ref = same.copy()
    tb = [list(c) for c in entry["colors"]]
    k = next(i for i,c in enumerate(entry["counts"]) if c)
    tb[k] = [1.0, 0.0, 0.0]
    apply(tb)
    after = np.empty(n*4, np.float32); attr.data.foreach_get("color", after)
    moved = int((np.abs(ref-after).reshape(-1,4)[:,:3].max(1) > 1e-6).sum())
    alpha_ok = bool(np.allclose(ref.reshape(-1,4)[:,3], after.reshape(-1,4)[:,3]))

    palette_ok = d_identity < 1e-6 and moved == entry["counts"][k] and alpha_ok
    palette_detail = (f"identity {{d_identity:.2e}}, moved {{moved}}/"
                      f"{{entry['counts'][k]}}, alpha {{alpha_ok}}")
except Exception as exc:
    palette_ok, palette_detail = False, str(exc)[:120]

json.dump({{
    "attributes": [c.name for c in cloud.data.color_attributes],
    "class_attrs": [a.name for a in cloud.data.attributes if a.name.startswith("class_")],
    "palettes": json.loads(cloud.get("figure_palettes") or "{{}}"),
    "palette_ok": palette_ok,
    "palette_detail": palette_detail,
    "layers": json.loads(cloud.get("figure_layers") or "{{}}"),
    "active": cloud.get("figure_active_layer"),
    "nodes": nodes,
    "graphs": graphs,
}}, open({out_json!r}, "w"))
''')
    run(["blender", "--background", blend, "--python", probe])
    if not osp.exists(out_json):
        record("blend is readable", False, "probe produced nothing")
        return
    data = json.load(open(out_json))
    record("blend is readable", True)

    for node in ("grade_saturation", "grade_brightcontrast", "grade_exposure",
                 "grade_gamma", "cloud_alpha"):
        record(f"grading node {node}", node in data["nodes"])

    record("layer table stored", bool(data["layers"]),
           f"{len(data['layers'])} layers")
    record("active layer stored", bool(data["active"]), str(data["active"]))

    # identity defaults: only `apply_to` layers may be non-neutral
    graded = set(cfg["color"]["apply_to"] or [])
    variants = {v["name"] for v in (cfg["color"]["variants"] or [])}
    offenders = []
    for name, entry in data["layers"].items():
        if name in graded or name in variants:
            continue
        for key, neutral in (("saturation", 1.0), ("contrast", 0.0),
                             ("brightness", 0.0), ("exposure", 0.0),
                             ("gamma", 1.0)):
            if abs(float(entry.get(key, neutral)) - neutral) > 1e-6:
                offenders.append(f"{name}.{key}={entry[key]}")
    record("ungraded layers keep identity defaults", not offenders,
           "; ".join(offenders[:4]))

    declared = {i["name"] for i in cfg["graphs"]["items"]}
    drawn = set(data["graphs"])
    record("declared graphs are drawn", declared <= drawn,
           f"declared {sorted(declared)}, drawn {sorted(drawn)}")

    unparented = [n for n, g in data["graphs"].items()
                  if "parent" in g and g["parent"] != f"{n}_edges"]
    record("graph nodes parented to edges", not unparented,
           f"loose: {unparented}" if unparented else "")

    for layer in ("semantic", "forest", "natural_habitat"):
        record(f"class attribute for {layer}",
               f"class_{layer}" in data.get("class_attrs", []),
               "" if f"class_{layer}" in data.get("class_attrs", []) else "missing")
    record("palette tables stored", bool(data.get("palettes")),
           f"{len(data.get('palettes', {}))} layers")
    record("palette recolour is exact and scoped", data.get("palette_ok") is True,
           data.get("palette_detail", ""))

    # Colour FIDELITY, not just structure: the stored linear values must decode
    # back to the exact hex in the palette config. Missing this check is what
    # let an sRGB/linear confusion render every figure lighter than specified.
    import numpy as _np
    from figlib.palettes import load_palettes as _lp, hex_to_rgb as _h2r

    def _lin2srgb(x):
        x = _np.clip(_np.asarray(x, float), 0, None)
        return _np.where(x <= 0.0031308, x * 12.92, 1.055 * x ** (1 / 2.4) - 0.055)

    palettes = _lp(cfg["data"]["palettes"], cfg["data"]["palette_overrides"])
    void_rgb = _np.rint(_np.asarray(cfg["void"]["color"]) * 255).astype(int)
    wrong = []
    for layer, entry in (data.get("palettes") or {}).items():
        spec = palettes.get(layer, {})
        for index, name in enumerate(entry["names"]):
            if index >= len(entry["colors"]):
                continue
            shown = _np.rint(_lin2srgb(entry["colors"][index]) * 255).astype(int)
            if index in entry.get("void", []) or name == "Unknown":
                want = void_rgb
            elif index < len(spec.get("colors", [])):
                want = _h2r(spec["colors"][index]).astype(int)
            else:
                continue
            if int(_np.abs(shown - want).max()) > 1:      # allow 1/255 rounding
                wrong.append(f"{layer}.{name} #{''.join('%02X' % v for v in shown)}"
                             f" != #{''.join('%02X' % v for v in want)}")
    record("stored colours decode to the specified hex", not wrong,
           "; ".join(wrong[:3]) if wrong else
           f"{sum(len(e['names']) for e in (data.get('palettes') or {}).values())} classes checked")

    heights = {n: g.get("height") for n, g in data["graphs"].items()}
    expected_height = cfg["graphs"]["height"]
    wrong = {n: h for n, h in heights.items()
             if h is not None and abs(h - expected_height) > 1e-3}
    record("graph height is an object transform", not wrong,
           f"expected {expected_height}, got {heights}" if wrong else
           f"height {expected_height}")


def check_degenerate():
    print("\ndegenerate cases")
    result = run([PY, SCRIPT, "--config", SAFE_NO_GRAPH, "--export"])
    record("ROI with no graph exports", result.returncode == 0,
           result.stderr[-400:] if result.returncode else "")

    result = run([PY, SCRIPT, "--config", SAFE_TILE, "--image", "--set",
                  "data.colors=['semantic']",
                  "data.default_color=semantic", "data.add_xyz=False",
                  "render.n_samples=4", "render.resolution=[200,140]"])
    record("restricting data.colors does not crash", result.returncode == 0,
           result.stderr[-400:] if result.returncode else "variants skipped")


def main(args):
    os.chdir(osp.dirname(osp.dirname(osp.abspath(__file__))))
    global SAFE_TILE, SAFE_NO_GRAPH
    SAFE_TILE = temp_config(TILE, "tile", {"data": {"subsample": 120000}})
    SAFE_NO_GRAPH = temp_config(TILE_NO_GRAPH, "nograph", {"data": {"subsample": 80000}})
    try:
        return _run_checks(args)
    finally:
        print(f"\ncleaned up {cleanup_temp(TILE, TILE_NO_GRAPH)} temporary files")


def _run_checks(args):
    with tempfile.TemporaryDirectory() as tmp:
        check_configs(args.all_configs)
        check_render_and_identity(tmp)
        check_export_and_roundtrip(tmp)
        check_degenerate()

    failed = [r for r in results if r[0] == FAIL]
    print(f"\n{len(results) - len(failed)}/{len(results)} checks passed")
    if failed:
        print("FAILED:")
        for _, name, detail in failed:
            print(f"  - {name}  {detail}")
    return 1 if failed else 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--all-configs", action="store_true",
                        help="Load every figure config, not just a sample")
    sys.exit(main(parser.parse_args()))
